<?php 
$array_grade_cadre=array(); 

$array_grade_cadre[0]='---'; 
$array_grade_cadre[1]="A"; 
$array_grade_cadre[8]="A10"; 
$array_grade_cadre[9]="A10BIS"; 
$array_grade_cadre[10]="A11"; 
$array_grade_cadre[2]="A4"; 
$array_grade_cadre[3]="A5"; 
$array_grade_cadre[4]="A6"; 
$array_grade_cadre[5]="A7"; 
$array_grade_cadre[6]="A8"; 
$array_grade_cadre[7]="A9"; 
$array_grade_cadre[11]="B"; 
$array_grade_cadre[12]="B4"; 
$array_grade_cadre[13]="BH"; 
$array_grade_cadre[14]="BH4"; 
$array_grade_cadre[15]="C"; 
$array_grade_cadre[16]="C4"; 
$array_grade_cadre[17]="D"; 
$array_grade_cadre[18]="D4"; 
$array_grade_cadre[19]="E"; 
$array_grade_cadre[20]="E4"; 
$array_grade_cadre[21]="Maribel"; 
?>